let token=localStorage.getItem('naicts_token'), user=JSON.parse(localStorage.getItem('naicts_user')||'null');
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=async(u,o={})=>{o.headers={...(o.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};const r=await fetch(u,o);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d};
function showDash(){if(!token||!user){return}$('#login').hidden=true;$('#dashboard').hidden=false;$('#userRole').innerHTML=`<span class="role">${esc(user.role)}</span>`;view('overview')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#email').value,password:$('#password').value})});token=d.token;user=d.user;localStorage.setItem('naicts_token',token);localStorage.setItem('naicts_user',JSON.stringify(user));showDash()}catch(x){$('#loginError').textContent=x.message}};
$('#logout').onclick=()=>{localStorage.removeItem('naicts_token');localStorage.removeItem('naicts_user');location.reload()};document.querySelectorAll('aside button[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
async function view(v){$('#viewTitle').textContent=v[0].toUpperCase()+v.slice(1);if(v==='overview')return overview();if(v==='posts')return posts();if(v==='events')return events();if(v==='media')return media()}
async function overview(){const s=await api('/api/admin/stats');$('#view').innerHTML=`<div class="stats">${[['Posts',s.posts],['Published',s.published],['Draft/Review',s.drafts],['Total Views',s.views],['Events',s.events]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div><div class="panel"><h3>Public-first publishing</h3><p>Visitors never create accounts. Staff use this protected CMS to create, review, approve and publish official NAICTS information.</p><p><b>Role:</b> ${esc(user.role)}</p></div>`}
async function posts(){const data=await api('/api/admin/posts');$('#view').innerHTML=`<div class="panel"><div class="toolbar"><b>All posts</b><button onclick="newPost()">+ New post</button></div><table class="table"><thead><tr><th>Title</th><th>Category</th><th>Status</th><th>Views</th><th>Actions</th></tr></thead><tbody>${data.map(p=>`<tr><td><b>${esc(p.title)}</b><br><small>${esc(p.author)}</small></td><td>${esc(p.category)}</td><td><span class="pill">${esc(p.status)}</span></td><td>${p.views}</td><td><button onclick="editPost(${p.id})">Edit</button> <button class="danger" onclick="deletePost(${p.id})">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function newPost(p={}){const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-card"><h2>${p.id?'Edit':'New'} post</h2><form id="postForm"><input name="title" placeholder="Title" value="${esc(p.title)}" required><input name="excerpt" placeholder="Short excerpt" value="${esc(p.excerpt)}"><select name="category"><option ${p.category==='News'?'selected':''}>News</option><option ${p.category==='Announcement'?'selected':''}>Announcement</option><option ${p.category==='PRO'?'selected':''}>PRO</option></select><textarea name="content" placeholder="Post content" required>${esc(p.content)}</textarea><input name="author" placeholder="Author" value="${esc(p.author||user.name)}"><input name="cover_image" placeholder="Cover image URL (optional)" value="${esc(p.cover_image)}"><select name="status"><option value="draft" ${p.status==='draft'?'selected':''}>Draft</option><option value="review" ${p.status==='review'?'selected':''}>Review</option><option value="approved" ${p.status==='approved'?'selected':''}>Approved</option><option value="published" ${p.status==='published'?'selected':''}>Published</option><option value="archived" ${p.status==='archived'?'selected':''}>Archived</option></select><label><input type="checkbox" name="featured" ${p.featured?'checked':''}> Featured</label><div class="modal-actions"><button type="button" class="secondary" onclick="this.closest('.modal').remove()">Cancel</button><button>Save post</button></div></form></div>`;document.body.appendChild(modal);$('#postForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const b=Object.fromEntries(fd.entries());b.featured=fd.has('featured');try{await api(p.id?'/api/admin/posts/'+p.id:'/api/admin/posts',{method:p.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});modal.remove();posts()}catch(x){alert(x.message)}}}
window.newPost=newPost;window.editPost=async id=>newPost((await api('/api/admin/posts')).find(x=>String(x.id)===String(id)));window.deletePost=async id=>{if(confirm('Delete this post?')){await api('/api/admin/posts/'+id,{method:'DELETE'});posts()}};
async function events(){const data=await api('/api/admin/events');$('#view').innerHTML=`<div class="panel"><div class="toolbar"><b>Events</b><button onclick="newEvent()">+ New event</button></div><table class="table"><tr><th>Event</th><th>Date</th><th>Venue</th><th></th></tr>${data.map(e=>`<tr><td>${esc(e.title)}</td><td>${esc(e.date)}</td><td>${esc(e.venue)}</td><td><button class="danger" onclick="delEvent(${e.id})">Delete</button></td></tr>`).join('')}</table></div>`}
window.newEvent=()=>{const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card"><h2>New event</h2><form id="eventForm"><input name="title" placeholder="Event title" required><input name="date" type="date" required><input name="time" placeholder="Time"><input name="venue" placeholder="Venue"><textarea name="description" placeholder="Description"></textarea><input name="image" placeholder="Image URL (optional)"><div class="modal-actions"><button type="button" class="secondary" onclick="this.closest('.modal').remove()">Cancel</button><button>Save event</button></div></form></div>`;document.body.appendChild(m);$('#eventForm').onsubmit=async e=>{e.preventDefault();await api('/api/admin/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});m.remove();events()}};window.delEvent=async id=>{if(confirm('Delete event?')){await api('/api/admin/events/'+id,{method:'DELETE'});events()}};
async function media(){ $('#view').innerHTML=`<div class="panel"><h3>Media storage</h3><p>Images are stored outside the Render filesystem using Cloudinary, then their secure URLs are saved in content records.</p><form id="mediaForm"><input id="mediaFile" type="file" accept="image/jpeg,image/png,image/webp,image/gif" required><button>Upload image</button></form><pre id="mediaResult"></pre></div>`;$('#mediaForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData();fd.append('image',$('#mediaFile').files[0]);try{const d=await api('/api/admin/upload',{method:'POST',body:fd});$('#mediaResult').textContent=d.url;alert('Upload successful. Copy the URL into a post or event.')}catch(x){alert(x.message)}}}
if (token \showDash();\showDash(); user) { showDash(); }
